"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
??? = '???'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'geeks',
    'jquery',
    'connection_app', # la partie connexion
    'contacts_app', # la partie gestion des contacts
    'django_dbconn_retry',
    'django_cleanup.apps.CleanupConfig',
    #'django_registration',# ---> Should make the field in english when models recreate again
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': str(os.path.join(BASE_DIR, "db.sqlite3"))
    #}
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'contacts_db',  
        'USER': '???',  
        'PASSWORD': '???',  
        'HOST': '???.?.?.?',  
        'PORT': '???',  
        'OPTIONS': {  
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  
        }  
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    #{
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, # un mot de passe d'au moins 8 caractères
        }
    },
    #{
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #},
    {
       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # au moins un caractère non numérique
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS=[
#    os.path.join(BASE_DIR,'/static')
#]
STATIC_ROOT=os.path.join(BASE_DIR,'statics') 
django_heroku.settings(locals())


MEDIA_URL = 'image/' # définit le répertoire des images
MEDIA_ROOT = os.path.join('')





# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'connection_app.User'

LOGIN_URL = 'login' # définit l'url de la page de connection

LOGIN_REDIRECT_URL = 'contacts' # définit l'url de renvoie une fois connecté
LOGOUT_REDIRECT_URL = 'login' # définit l'url de renvoie une fois deconnecté

SESSION_EXPIRE_AT_BROWSER_CLOSE = True # la session se ferme à la fermeture du navigateur


#import environ

#env = environ.Env()
#environ.Env.read_env()

#SMTP CONFIGURATION
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = '???'
EMAIL_HOST = '???'
EMAIL_PORT = ???
#EMAIL_USE_START??? = True
EMAIL_USE_??? = True # protocole TLS pour l'envoi d'email
???_ENABLED = True
EMAIL_HOST_??? = '???'
EMAIL_HOST_??? = '???'
#env('RECIPIENT_ADDRESS')


#SELENIUM_LOGIN_START_PAGE = '' #pour definir la redirection quand login par selenium
