# Generated by Django 4.1.2 on 2023-03-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
